### ISSUE TITLE
hg19/GRCh37 SV VCF

### ISSUE THREAD

**Issue by dantaki** [Illumina/Polaris#11]
The current SV VCF on this github is in build GRCh38. The BAMs hosted on ENA are in ensembl GRCh37 (without decoy). 

Is there a GRCh37 SV VCF I can refer too, or should I liftOver the positions myself? 

Note:
```
To download VCF for hg38, please do:

wget https://s3-us-west-1.amazonaws.com/illumina-polaris-v2.1-sv-truthset/all_merge.vcf.gz
wget https://s3-us-west-1.amazonaws.com/illumina-polaris-v2.1-sv-truthset/all_merge.vcf.gz.tbi

hg19 is coming in mid March.

```

**Comment by traxexx** [comment]
No. We end up not generating GRCH37 version. I can do the liftover for you. It will be equivalent to UCSC liftover tools. Let me know if you need.

**Comment by dantaki** [comment]
I can do the liftOver myself using the UCSC executable. Thanks for the clarification.
