### ISSUE TITLE
ENA links are currently returning an error from the ENA website

### ISSUE THREAD

**Issue by Phillip-a-richmond** [Illumina/Polaris#14]
The ENA links are currently returning a server error from the ENA website.

The ERR links are not visible on the new ENA website either. 

I've submitted a ticket to ENA regarding the issue, to see if it's temporary or an error from the migration to the new website. 

Any extra insight is useful, or another option for fastq download as well.

Thanks,
Phil

**Comment by Phillip-a-richmond** [comment]
This must have been a temporary issue with the ENA. Links are active again.

**Comment by MBekritsky** [comment]
Thanks for keeping us posted @Phillip-a-richmond! Glad the issue resolved itself

-- Mitch
