### ISSUE TITLE
Error in Sex Labeling

### ISSUE THREAD

**Issue by Phillip-a-richmond** [Illumina/Polaris#15]
Hello,

I'm confident that you have mislabeled the sex of individual:

HG01683

It is listed as a male, but after using this sample as a trio for testing our new tool we are confident that it is a female. The sex of two other children was verified as male during this process (HG02773 and HG00664). 

Cheers,
Phil

**Comment by MBekritsky** [comment]
Hi Phil,

Thank for bringing this to our attention -- I've checked the Coriell website and it looks like they've listed the sex of [HG01683](https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=HG01683) as male.  I don't doubt that you're seeing something fishy, but it would be helpful if you could provide us some additional context for what you're seeing.  Would you mind sharing a bit more about your observations?

All the best,

Mitch

**Comment by Phillip-a-richmond** [comment]
Hi Mitch,

So we have developed a tool which can generate genotypes for a sample without the need for reference-based mapping (happy to share the link when it's on biorXiv later next week).  We used three trios to show that our tool can get ancestry and sex typing from a limited number of genotyped sites, after converting to VCF and plugging into Peddy (https://github.com/brentp/peddy).  

Everything looks good regarding the trio assignments, the ancestry inference, but for the European trio we used, the child HG01683 was identified as female (see attached images).

![AncestryInferencePeddy](https://user-images.githubusercontent.com/16579982/75478509-f45ac080-5952-11ea-8eb5-cdd06a964f92.png)
![RelatednessTypingPeddy](https://user-images.githubusercontent.com/16579982/75478514-f58bed80-5952-11ea-80ba-bf1191702068.png)
![SexTypingPeddy](https://user-images.githubusercontent.com/16579982/75478516-f6248400-5952-11ea-9dbb-08b83932f972.png)


I also mapped the data and pulled up in IGV, het sites and coverage of X clearly indicates female.

![EuroChildIsFemale](https://user-images.githubusercontent.com/16579982/75478552-03417300-5953-11ea-94d8-eed0a68edec6.png)


But as I write this, the plot thickens!!! So I figured I should probably check the Y chromosome...

![EuroChildIsFemale_withYChrom2](https://user-images.githubusercontent.com/16579982/75478572-0e949e80-5953-11ea-96a8-6f2edb285d5a.png)
![EuroChildIsFemale_withYChrom](https://user-images.githubusercontent.com/16579982/75478573-0f2d3500-5953-11ea-8d1d-41b273993dfd.png)

And it looks like the the individual is...XXY! Is this information listed elsewhere? Very unusual but quite thought provoking.

I suppose an XXY individual appears as a male, but for other researchers this may be useful to know as it may affect analysis pipelines. 

Cool stuff! Sorry for the long post, I was confident this was a female based on the X and the peddy analysis. 

Let me know what extra information you need from me if you contact Coriell or the individuals.

Cheers,
Phil

**Comment by MBekritsky** [comment]
Hi Phil,

I dug around a little bit and we've seen some indications before that this might be the case (that I missed...).  I'm not sure what our responsibilty is to report this back to Coriell or the individuals, but it's probably worth looking into.  I will reach out to some folks and will let you know if I need any additional information from you.

Thanks for catching this!  I added a note in the sample description and will close the issue for now.

All the best,

Mitch
