### ISSUE TITLE
Interactive access to the data via Basemount

### ISSUE THREAD

**Issue by JRodrigoF** [Illumina/Polaris#17]
Hi, 

I discovered haploid genotypes in the merged.vcf.gz file I downloaded time ago. Then I found out that there is a more recent update of this and other files in the folder "GVCF Genotyper 2.1". I would like to download it via command line. However I found too the following instructions not to be valid anymore:

https://github.com/Illumina/Polaris/wiki/How-to-interactively-access-the-data-with-BaseMount

The Polaris data is not listed under the Projects folder. 

I also tried using the following commands:

~/bin/bs --access-token=XXXX --api-server=https://api.euc1.sh.basespace.illumina.com/ get project --id=2265263
ERROR: *** BASESPACE.COMMON.AUTHENTICATION_FAILURE: Please ensure that valid credentials are being provided for this API call (JWT authentication is not supported with this request) ***

~/bin/bs --access-token=XXXX --api-server=https://api.basespace.illumina.com/ get project --id=2265263
ERROR: *** BASESPACE.COMMON.INSUFFICIENT_RESOURCE_PERMISSIONS: Sorry but this requires BROWSE access to this Project resource. ***

Thanks

**Comment by janinl** [comment]
Hi @JRodrigoF 

If the data is not listed under the Projects folder, could you check that it is listed in your BaseSpace web GUI? If it is visible there, your CLI-BaseMount authentication probably points to a different account or workgroup. You'd simply need to rerun the authentication bit.

The access token that you had included above (I edited your post, as anyone on the internet could have accessed your account with this access token, including deleting data and launching apps) pointed to an account with only 1 project, which wasn't a Polaris one.

**Comment by JRodrigoF** [comment]
Hi @janinl , 

Thanks for the reply. I have repeated several times the authentication part. Every time I have to log in via browser to my Illumina/BaseSpace account, which indeed shows the Polaris data in my project folder (since I imported it beforehand from freedata). So command line and GUI-based should be sync, right? And my access token should have access to it, no?

But I still cannot see the project within the mounted folder neither neither get pass over the messages above if I try bs 

I downloaded already the file via the browser, but still this way should be doable too.

**Comment by janinl** [comment]
I'm really not sure where the problem is...

Make sure you don't use `--access-token=XXXX --api-server=https://api.basespace.illumina.com/ ` anymore once you authenticated: Your new access token should be saved (by `bs auth`) in ~/.basespace/default.cfg . You could also check that this file was created recently, and delete it before trying to auth again...

**Comment by JRodrigoF** [comment]
Hi, 

I solved the issue by authenticating again but specifying the server:

~/bin/bs auth --force --api-server=https://api.euc1.sh.basespace.illumina.com/

by specifying the server https://api.basespace.illumina.com/ , which is the default, it seems my GUI-based settings are not sync to this sever. 

Thanks for the infos
