### ISSUE TITLE
NA12877 and NA12878 genotypes

### ISSUE THREAD

**Issue by hannespetur** [Illumina/Polaris#2]
Hello,

the release note for VC1.0 it is stated that variants are reported for 221 individuals, including NA12878 and NA12877, however I cannot find those two individuals in the VC1.0 VCF file.

```sh
$ bcftools view -s NA12877 vc1_0.vcf.gz
Error: subset called for sample that does not exist in header: "NA12877". Use "--force-samples" to ignore this error.
$ bcftools view -s NA12878 vc1_0.vcf.gz
Error: subset called for sample that does not exist in header: "NA12878". Use "--force-samples" to ignore this error.
```

Are these two samples called something different?

All the best,
Hannes

**Comment by eberle** [comment]
Hi Hannes,

I think that these were accidentally omitted and that this file just contains just the Diversity and PGx samples. The person that made this file will be back next week and we will update this call set to the newest ones, including these samples. In the meantime, if you could email me directly (meberle@illumina.com) we can get those samples to you sooner.

Cheers,
-Mike

**Comment by hannespetur** [comment]
Thank you!
