### ISSUE TITLE
Are short-variant genotypes available for any of the cohorts?

### ISSUE THREAD

**Issue by tfenne** [Illumina/Polaris#7]
Hi!  Thanks for assembling such a great resource.  I'm curious if short-variant genotypes on any of the cohorts are available anywhere yet?  The [Joint Genotyping Methods](https://github.com/Illumina/Polaris/wiki/Joint-Genotyping-Methods) page mentions that a callset has beed made using gvcfgenotyper, but there's no mention of availability.

I did take the time to check the Diversity cohort in ENA (just sequence data that I could see) and BaseSpace (I get a 403 forbidden!), but didn't find anything.  A short variant callset would be super useful, so I'd appreciate any information on whether it's available or is forthcoming.  Thanks!

**Comment by tfenne** [comment]
From talking to a colleague, I'm given to believe that the data is available in BaseSpace.  However, as mentioned above I get an error trying to access.  I followed the instructions to log in at https://euc1.sh.basespace.illumina.com first and then open this link: https://euc1.sh.basespace.illumina.com/s/ec3X5yWG3QEP .  When using basespace classic it gives me a 403.  When using the new basespace version I get a pop up with:

> Invalid Invite
> We're sorry, but the current invitation is invalid or no longer active

Would it be possible to get an updated invite link please?

**Comment by MBekritsky** [comment]
Hi Tim,

Apologies, I really need to update where to access the data on BaseSpace! All my advice below is in relation to new BaseSpace.

You can get the data on [basespace.illumina.com](basespace.illumina.com) through the ['Public Data'](https://basespace.illumina.com/datacentral) section, where we have the Diversity and Kids cohort available (just type Polaris in the search bar with 'Search Public Data' on the upper right of the page).  I'm not sure if the invite link gets updated or is static, so this is the surest way of getting access to the cohorts on BaseSpace. Both projects have single sample VCFs for all samples on WGSv7.0.1 and Dragen v2.6.5.  You can see those by clicking on the 'Biosamples' tab on each project and looking under 'Datasets'.

<img width="1679" alt="screen shot 2019-01-11 at 11 41 43 am" src="https://user-images.githubusercontent.com/1394999/51047214-f10d4580-1595-11e9-8748-3fb68303abeb.png">

In addition, we do have GVCF genotyper results for the diversity cohort available in the project as well.  If you look under the 'Analyses' tab, the first result there should be the GVCF genotyper output.  The joint genotyping output is from WGSv7.0.1.

<img width="1680" alt="screen shot 2019-01-11 at 11 42 32 am" src="https://user-images.githubusercontent.com/1394999/51047259-0d10e700-1596-11e9-8f05-0bf6202ddd85.png">

I think this should be all that you're after, but if you have any further questions or requests, please let me know and I'll see what I can do.

Mitch

**Comment by tfenne** [comment]
Thank worked!  Thanks so much Mitch.
