### ISSUE TITLE
Reference to Illumina Polaris data set

### ISSUE THREAD

**Issue by JRodrigoF** [Illumina/Polaris#9]
Hi, 

Any preferred way to reference the Polaris data cohorts? (e.g. Diversity cohort)
I understand there is no specific publication, but rather a data resource that could be linked to this git hub repo, or [ENA](https://www.ebi.ac.uk/ena/data/view/PRJEB20654), or its [NCBI Bioproject](https://www.ncbi.nlm.nih.gov/bioproject/387148)

Best
Rodrigo

**Comment by MBekritsky** [comment]
Hi Rodrigo,

For now, our preference would be to refer to the data by the repo and either the ENA or NCBI Bioproject ID.  We are working on a publication that will make it easier to cite the resource in the future.  Once we have the publication out, I will add information to the homepage about how to cite Polaris.

Thanks for asking, and if there's anything else, just let me know.

Mitch

**Comment by twesigomwedavid** [comment]
Hello @MBekritsky ,

How about acknowledgements. Is there any preferred statement?

Thanks 

David

**Comment by MBekritsky** [comment]
Hi @twesigomwedavid,

Just a general acknowledgment is fine, thanking Illumina for the resource.  If you'd like to run any specific language by me, you can email me at mbekritsky@illumina.com.

Thanks!

Mitch
